name: Upload Image via Dispatch

on:
  repository_dispatch:
    types: [upload-image]

jobs:
  upload-image-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Save Image
        run: |
          mkdir -p images
          echo "${{ github.event.client_payload.image_base64 }}" | base64 --decode > images/${{ github.event.client_payload.filename }}

      - name: Commit Image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/${{ github.event.client_payload.filename }}
          git commit -m "Upload image via GitHub Action: ${{ github.event.client_payload.filename }}"
          git push origin main
